services:
  - type: web
    name: phishing-detector-api
    env: python
    buildCommand: "pip install -r requirements.txt && python train_model.py"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
